# .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# Bash completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

if [ -f `brew --prefix`/opt/homebrew/etc/bash_completion.d ]; then
  . `brew --prefix`/opt/homebrew/etc/bash_completion.d
fi

[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

PATH=$PATH:$HOME/.local/bin:$HOME/bin

# gunubin
PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"

export PATH

. `brew --prefix`/etc/profile.d/z.sh

source ~/enhancd/init.sh

# GOENV
export GOENV_ROOT=$HOME/.goenv
export PATH=$GOENV_ROOT/bin:$PATH
eval "$(goenv init -)"



# GOLANG
export GOENV_DISABLE_GOPATH=1
export GOPATH=$HOME/work/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH/bin
export GO111MODULE=on

export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

export KUBECONFIG=${HOME}/.kube/config-jupiter kubectl get all

export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

export GPG_TTY=$(tty) # for GPG

# for NVIM
export XDG_CONFIG_HOME=~/.config

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


if [ -f ~/.bash_env ]; then
  source ~/.bash_env
fi

# Functions

function aws-profile-switch() {
    local profile="$(grep '\[' ~/.aws/credentials | sed -s -e 's/\[//' -e 's/\]//' | peco)"
    export AWS_PROFILE="$profile"
    # AWS CLI v2では不要
    # export AWS_DEFAULT_PROFILE="$profile"
}

function display-aws-profile() {
    if [ -n "$AWS_PROFILE" ]; then 
        echo -n "AWS[$AWS_PROFILE]"
        exit
    fi
    echo -n "AWS[NO SET]"
}

# grep text
function gtext() {
    local file_path="$(grep $1 -rl . | peco)"
    vim $file_path
}

# find file
function ffile() {
    local file_path="$(find . -type f -name *$1* | peco)"
    vim $file_path
}
