set t_Co=256
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set expandtab    "タブをスペースにする
"set noet          "タブをタブ文字にする
set backspace=2 " バックスペース有効化
set number
set nobackup                   " バックアップを作らない
set noswapfile                 " swapファイルを作らない
set autoread                   " 他で書き換えられたら自動で読み直す
set laststatus=2               "常にステータス行を表示
set encoding=utf-8
set fileencodings=utf-8,iso-2022-jp,euc-jp,sjis
set fileformats=unix,dos,mac
set hlsearch
set incsearch
set mouse=

filetype off

"vim-plug Scripts-----------------------------

call plug#begin()
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'lambdalisue/fern.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'github/copilot.vim'
Plug 'mattn/vim-lsp-settings'

" for golang
Plug 'mattn/vim-goimports'
"Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

Plug 'glidenote/memolist.vim'
Plug 'reireias/vim-cheatsheet'
Plug 'tpope/vim-fugitive'

Plug 'w0ng/vim-hybrid'

" for Typescript + react
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install --frozen-lockfile --production',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'svelte', 'yaml', 'html'] }

" for terraform
Plug 'hashivim/vim-terraform'

" NeoVim限定のplugin
if has('nvim')
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.4' }
Plug 'EdenEast/nightfox.nvim'
endif
call plug#end()

"end vim-plug Scripts-------------------------

" NeoVim限定の設定
if has('nvim')
endif

syntax on

"let g:hybrid_custom_term_colors = 1
"let g:hybrid_reduced_contrast = 1 " Remove this line if

let g:memolist_path = "~/.cache/memolist" " メモの保存先
let g:cheatsheet#cheat_file = '~/.cheatsheet.md' " cheatsheetの保存先
let g:airline#extensions#tabline#enabled = 1 "タブラインを有効化
let g:airline#extensions#tabline#buffer_idx_mode = 1 "バッファ番号を表示

"vim-go setting
"ref. https://github.com/hnakamur/vim-go-tutorial-ja/blob/master/README.md
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
"let g:go_metalinter_autosave = 1
"let g:go_metalinter_command = 'golangci-lint'
"let g:go_metalinter_autosave_enabled = ['gosimple', 'errcheck', 'gosec', 'staticcheck', 'bodyclose']
"let g:go_metalinter_enabled = ['vet', 'gosimple', 'errcheck', 'gosec', 'staticcheck', 'cyclop', 'bodyclose']



set background=dark
colorscheme hybrid
"colorscheme nightfox

nnoremap s <Nop>

" 画面分割
nnoremap <C-a>- :<C-u>sp<CR>
" <Bar> は|
nnoremap <C-a><Bar> :<C-u>vs<CR>

" 分割した画面間の移動
nnoremap <C-a>j <C-w>j
nnoremap <C-a>k <C-w>k
nnoremap <C-a>l <C-w>l
nnoremap <C-a>h <C-w>h

" <esc>のキーバインド
noremap <C-j> <esc>
noremap! <C-j> <esc>

" for HHKB
nnoremap ; :

" for lsp
" Remap keys for gotos
nmap <silent> gd <cmd>LspDefinition<CR>
nmap <silent> gy <cmd>LspTypeDefinition<CR>
nmap <silent> gi <cmd>LspImplementation<CR>
nmap <silent> gr <cmd>LspReferences<CR>

" fern.vim
" スペースe でエクスプローラが立ち上がる
nmap <space>e <Cmd>:Fern . -drawer<CR>

" memolist
nnoremap <Leader>mn  :MemoNew<CR>
nnoremap <Leader>ml  :MemoList<CR>
nnoremap <Leader>mg  :MemoGrep<CR>

" airline
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab

" Find files using Telescope command-line sugar. using telescope.nvim
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
