set t_Co=256
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set expandtab    "タブをスペースにする
"set noet          "タブをタブ文字にする
set backspace=2 " バックスペース有効化
set number
set nobackup                   " バックアップを作らない
set noswapfile                 " swapファイルを作らない
set autoread                   " 他で書き換えられたら自動で読み直す
set laststatus=2               "常にステータス行を表示
set encoding=utf-8
set fileencodings=utf-8,iso-2022-jp,euc-jp,sjis
set fileformats=unix,dos,mac
set hlsearch
set incsearch

filetype off

"vim-plug Scripts-----------------------------

call plug#begin()
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'EdenEast/nightfox.nvim'
Plug 'github/copilot.vim'
Plug 'glidenote/memolist.vim'
Plug 'reireias/vim-cheatsheet'

Plug 'w0ng/vim-hybrid'
call plug#end()

"end vim-plug Scripts-------------------------


syntax on

"let g:hybrid_custom_term_colors = 1
"let g:hybrid_reduced_contrast = 1 " Remove this line if

let g:memolist_path = "~/.cache/memolist" " メモの保存先
let g:cheatsheet#cheat_file = '~/.cheatsheet.md' " cheatsheetの保存先
let g:airline#extensions#tabline#enabled = 1 "タブラインを有効化
let g:airline#extensions#tabline#buffer_idx_mode = 1 "バッファ番号を表示



set background=dark
colorscheme hybrid
"colorscheme nightfox

nnoremap s <Nop>

" 画面分割
nnoremap ss :<C-u>sp<CR>
nnoremap sv :<C-u>vs<CR>
" 分割した画面間の移動
nnoremap sj <C-w>j
nnoremap sk <C-w>k
nnoremap sl <C-w>l
nnoremap sh <C-w>h
" 分割した画面を移動
nnoremap sJ <C-w>J
nnoremap sK <C-w>K
nnoremap sL <C-w>L
nnoremap sH <C-w>H

" <esc>のキーバインド
noremap <C-j> <esc>
noremap! <C-j> <esc>

" for HHKB
nnoremap ; :

" for coc

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" coc explorer
" スペースe でエクスプローラが立ち上がる
nmap <space>e <Cmd>CocCommand explorer<CR>


" memolist
nnoremap <Leader>mn  :MemoNew<CR>
nnoremap <Leader>ml  :MemoList<CR>
nnoremap <Leader>mg  :MemoGrep<CR>

" airline
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab

